source "https://rubygems.org"

# Specify your gem's dependencies in demo.gemspec
gemspec

gem "slick", path: "#{__dir__}/../slick"
gem "blognami", path: "#{__dir__}/../blognami"

gem "puma", "~> 5.6"

gem "rake", "~> 13.0"
gem "minitest", "~> 5.0"

gem "faker", "~> 2.21"

gem "sqlite3", "~> 1.4"
