
export default {
    create(){
        return [
            // Original
            'portal',
            'www',
            'api',
            'admin',
            'mail',
            'ftp',
            'blog',
            'app',
            'help',
            'support',
            'status',
            'docs',

            // Infrastructure
            'smtp',
            'imap',
            'pop',
            'ns1',
            'ns2',
            'ns3',
            'ns4',
            'cdn',
            'vpn',
            'ssh',
            'dns',
            'proxy',
            'gateway',
            'server',
            'node',
            'cluster',
            'relay',
            'mx',
            'firewall',
            'loadbalancer',
            'lb',
            'cache',
            'redis',
            'db',
            'database',
            'monitor',
            'logging',
            'syslog',
            'backup',

            // Brand
            'blognami',
            'pinstripe',
            'pinstripejs',

            // Common web
            'login',
            'signin',
            'signup',
            'register',
            'dashboard',
            'account',
            'billing',
            'settings',
            'profile',
            'search',
            'home',
            'about',
            'contact',
            'news',
            'shop',
            'store',
            'forum',
            'wiki',
            'download',
            'downloads',
            'pricing',
            'checkout',
            'oauth',
            'auth',
            'sso',
            'callback',
            'assets',
            'static',
            'media',
            'images',
            'files',
            'upload',
            'uploads',
            'css',
            'js',
            'fonts',

            // Abuse-prone
            'test',
            'demo',
            'staging',
            'dev',
            'prod',
            'production',
            'example',
            'info',
            'secure',
            'official',
            'newsletter',
            'noreply',
            'no-reply',
            'postmaster',
            'abuse',
            'webmaster',
            'hostmaster',
            'root',
            'administrator',
            'mailer-daemon',
            'security',
            'spam',
            'phishing',
            'null',
            'undefined',
            'localhost',
            'local',
            'internal',
            'private',
            'public'
        ];
    }
};
